# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type_id',
            field=models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Javascript'), (3, '数据结构与算法'), (4, '机器学习'), (5, '操作系统'), (6, '数据库')], default=1, verbose_name='商品种类'),
        ),
    ]
